### ISSUE TITLE
GUI doesn't work

### ISSUE THREAD

**Issue by Cooplix** [alkeicam/devjam#8]
![image](https://github.com/user-attachments/assets/4598dc17-62c4-425d-a0a4-bd88519a7d6d)

**Comment by alkeicam** [comment]
@Cooplix daj znać prosze jaki system operacyjny i którą wersję pobrałeś?

**Comment by Cooplix** [comment]
@alkeicam 
Windows 11, version 23H2
wersja aplikacji 1.0.43

jakiś czas temu działało poprawnie, reinstlacja nie pomogła

**Comment by alkeicam** [comment]
@Cooplix  przygotuję dla ciebie specjalną wersję z dodatkową diagnostyką i dam znać jak będzie do pobrania

**Comment by alkeicam** [comment]
fixed in version 1.0.47
